### ISSUE TITLE
Can the value in the response be taken from the request?

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/simplehttpserver#26]
# example
```
rules:
  # HTTP Requests
  - match: GET /path1
    response: |
              HTTP/1.0 301 Moved Permanently
              Location: {{param.url}}   # or Location: http://{{param.url.base64decode}}
              Server: httpd/2.0
              x-frame-options: SAMEORIGIN
              x-xss-protection: 1; mode=block
              Date: Fri, 16 Apr 2021 14:30:32 GMT
              Content-Type: text/html
              Connection: close

              {{body}}
```
